### ISSUE TITLE
no such file or directory 'react-apollo-form\dist\lib\cli.js'

### ISSUE THREAD

**Issue by JMGonzalezR** [wittydeveloper/react-apollo-form#20]
I'm trying to install this, but no luck. I got some Warnings and an error:

`npm WARN deprecated apollo-codegen@0.19.1: The 'apollo-codegen' command has been replaced with the more-powerful 'apollo' CLI.`

`npm ERR! path ...\node_modules\react-apollo-form\dist\lib\cli.js
npm ERR! enoent ENOENT: no such file or directory, chmod '...\node_modules\react-apollo-form\dist\lib\cli.js'`

**Comment by wittydeveloper** [comment]
Hi everybody,

Sorry for the delay.

I found that the issue is linked to the updates of dependencies of `react-apollo-form` to incompatible versions when using `npm`.

I strongly advise to use `yarn` while I update all dependencies of the project.
This may take time because `apollo-codegen` project had a huge refactoring during the last months.

If you cannot switch to `yarn`, I strongly advice you to generate a `package-lock.json` from the `yarn.lock` file by using this tool: https://github.com/imsnif/synp.

Sorry for the inconvenience,

Cheers

**Comment by wittydeveloper** [comment]
If you are using `npm`, please update to the `react-apollo-form@0.1.7-alpha.1` version in order to fix this bug.

**Comment by JMGonzalezR** [comment]
Thanks a lot, will try this and let you know the results

**Comment by christianjul** [comment]
I have this issue with yarn as well. There are no js files in `dist`, seems like a tsc step has been missed somewhere in the build or install process

**Comment by christianjul** [comment]
Upgrading to `0.1.7-alpha1` fixed that.

**Comment by wittydeveloper** [comment]
Thanks @christianjul,

I definitely should publish this version as a new stable patch ASAP.

**Comment by wittydeveloper** [comment]
`react-apollo-form@0.1.7` published with the stable fix. ✅
