### ISSUE TITLE
What about handling active, dirty, touched, valid, etc?

### ISSUE THREAD

**Issue by aryzing** [wittydeveloper/react-apollo-form#30]
How should the state of the user interaction with the form be handled? Other libs provide vars such as active, dirty, touched, valid to allow for the configuring of this behavior.

**Comment by wittydeveloper** [comment]
Hi @aryzing 👋 

Please know that `react-apollo-form` is still in beta, new maintainers will soon join the project in order to deliver a stable and full-featured release.

This current version only support a subset of what you can expect from other libraries like `redux-form` or `formik`.
As explained in ["Form Rendering customisation with renderers"](https://github.com/wittydeveloper/react-apollo-form/wiki/Form-Rendering-customisation-with-renderers), only the following state properties are accessible:
- `isDirty: boolean;`
- `isSaved: boolean;`
- `hasError: boolean;`


Please continue to follow this project in order to get updates. 🙇

**Comment by wittydeveloper** [comment]
Hi @aryzing ,

If you have the opportunity, please look at the full rewrite of this library that provides better state APIs:
https://github.com/frontier-forms/frontier-forms

Thanks,
