### ISSUE TITLE
Maintenance state

### ISSUE THREAD

**Issue by nicodmf** [wittydeveloper/react-apollo-form#33]
As this package should be replaced by another. Can we have a hope on this package maintenability ? 

We must finish the development of our application in this month, so we can't wait april for the new package. 

And for all other people using this package, this could be an important point too.

**Comment by wittydeveloper** [comment]
Hi @nicodmf,

Thanks for sharing you concern.

The only breaking change with `react-apollo-form` will be the underlying architecture (ex: we will no use `react-jsonschema-form` anymore), **however**, the API will be close to the `react-apollo-form` ones.

I will work on trying to provide some migration tools, libraries and documentation, since the idea is not to drop  `react-apollo-form` definitely but just to make it stronger and more powerful.

I will keep you updated in the Issue #31.

Cheers,
